version: '3'

services: 
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./tls:/usr/src/app/tls
    ports:
      - 9229:9229
    command: npm run debug