version: '3'

services:
  web:
    build: .
    ports:
      - 443:443
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - ./tls:/usr/src/app/tls
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - ./db:/data
    entrypoint: redis-server --appendonly yes
    restart: always